name: Build and Release APK
on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    branches: [ "*" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Prepare NDK dir for caching ( workarounds for https://github.com/actions/virtual-environments/issues/1337 )
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/ndk
          sudo chmod -R 777 /usr/local/lib/android/sdk/ndk
          sudo chown -R $USER:$USER /usr/local/lib/android/sdk/ndk

      - name: install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Install JS dependencies
        run: npm install

      - name: Build Android app (from subfolder)
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: Move to release
        run: |
          cp ./android/app/build/outputs/apk/release/app-release.apk vuln_bank_mobile_app.apk

      - name: Launch Ostorlab Full Scan with just Login Credential
        uses: Ostorlab/ostorlab_actions@v2.0.0
        with:
          scan_profile: fast_scan
          asset_type: android-apk
          target: ./vuln_bank_mobile_app.apk
          scan_title: Ostorlab Insecure App Workflow
          ostorlab_api_key: ${{ secrets.OSTORLAB_API_KEY }}